import React from 'react'

export const metadata = {
  title: "Contract page",
  description: "Generated by create next app",
}

export default function page() {
  return (
    <div>
      this is contract page
    </div>
  )
}
