import React from 'react'

export const metadata = {
  title: "About page",
  description: "Generated by create next app",
}

export default function About() {
  return (
    <div className='mt-6'>
        <h1> This is about page </h1>
    </div>
  )
}
